# Generated by Django 5.1.1 on 2024-09-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_rename_mymodel_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='file_field',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='file_path_field',
        ),
    ]
